### ISSUE TITLE
Multi-GPU support

### ISSUE THREAD

**Issue by julien-arch** [junyanz/CycleGAN#10]
It is possible to choose which GPU gets to do the job, it would be great to also allow to use multiple GPUs at the same time.

**Comment by junyanz** [comment]
We are looking into multi-GPU support in our pytorch implementation.

**Comment by ianni67** [comment]
Hello Jun-Yan, your work is great and I'm closely following it for my research purposes. 
As I'm building my application using python, and running it on a server with multiple GPUs, which I share with colleagues, I'm definitely interested in your pytorch implementation. 
I read you planned to release it in a couple of days, I can't wait for that moment to come :-)

**Comment by kabrio** [comment]
Any news concerning multi GPU support?

**Comment by junyanz** [comment]
Check out our [pyTorch](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix) implementation for multi-GPU support.
