### ISSUE TITLE
How to use cycleGAN to train on my own dataset ?

### ISSUE THREAD

**Issue by sunshinevirgo21** [junyanz/CycleGAN#100]
Hi, I'm very new to this. What is the use of putting the comman --name and --model while running the command line ? secondly How to use cycleGAN to train on my own dataset ?

**Comment by junyanz** [comment]
`--name` is the experiment name. ``--model`` indicates which learning method to use (e.g., 'cycle_gan', 'pix2pix'). Please check out the [options.lua](https://github.com/junyanz/CycleGAN/blob/master/options.lua) for more details.
See [here](https://github.com/junyanz/CycleGAN#setup-training-and-test-data) for how to train on your own dataset.

**Comment by sunshinevirgo21** [comment]
Thanks :)
