### ISSUE TITLE
Size mismatch RuntimeError on training with FINE_SIZE more than 256.

### ISSUE THREAD

**Issue by siddhartha-iitd** [junyanz/CycleGAN#101]
Using LOAD_SIZE=640, FINE_SIZE=256 for training works fine. However, using LOAD_SIZE=640, FINE_SIZE=512 or LOAD_SIZE=512, FINE_SIZE=512 throws a RunTimeError shown below:
<pre>Traceback (most recent call last):
  File &quot;./train.py&quot;, line 34, in &lt;module&gt;
    model.optimize_parameters()
  File &quot;bicyclegan/BicycleGAN/models/bicycle_gan_model.py&quot;, line 209, in optimize_parameters
    self.forward()
  File &quot;bicyclegan/BicycleGAN/models/bicycle_gan_model.py&quot;, line 106, in forward
    self.z_encoded, self.mu, self.logvar = self.encode(self.real_B_encoded)
  File &quot;bicyclegan/BicycleGAN/models/bicycle_gan_model.py&quot;, line 83, in encode
    mu, logvar = self.netE.forward(input_image)
  File &quot;/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/data_parallel.py&quot;, line 121, in forward
    return self.module(*inputs[0], **kwargs[0])
  File &quot;/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py&quot;, line 477, in __call__
    result = self.forward(*input, **kwargs)
  File &quot;bicyclegan/BicycleGAN/models/networks.py&quot;, line 602, in forward
    output = self.fc(conv_flat)
  File &quot;/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py&quot;, line 477, in __call__
    result = self.forward(*input, **kwargs)
  File &quot;/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py&quot;, line 91, in forward
    input = module(input)
  File &quot;/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py&quot;, line 477, in __call__
    result = self.forward(*input, **kwargs)
  File &quot;/usr/local/lib/python3.6/dist-packages/torch/nn/modules/linear.py&quot;, line 55, in forward
    return F.linear(input, self.weight, self.bias)
  File &quot;/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py&quot;, line 1024, in linear
    return torch.addmm(bias, input, weight.t())
RuntimeError: size mismatch, m1: [1 x 1024], m2: [256 x 8] at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:249
</pre>

Could you please help me find out how can I train the model for FINE_SIZE values of 512 or more ?
Thanks!

**Comment by junyanz** [comment]
I think the question was posted in the wrong repo. This question is related to BicycleGAN. 
The default generator in BicycleGAN is `unet_128` or `unet_256`. It now only supports 128 or 256. For 512 images, you can either use `resnet_256` or add a few layers to unet_256.

**Comment by siddhartha-iitd** [comment]
Thanks @junyanz for reply. I just made that change and it works :)
Thanks again!
