### ISSUE TITLE
Question about the input in cyclegan

### ISSUE THREAD

**Issue by amy-hyunji** [junyanz/CycleGAN#107]
Hi I want to ask question about the input channels when training cyclegan.
I tried to have input channel as 'L':1 channel and output as 'RGB':3 channels.
However, there was an error message saying that there is trouble on number of channels.
I thought that this might be because the input and output should have same number of channels.
Is my prediction right or is it due to somewhere else in code?

Thank you :)

**Comment by junyanz** [comment]
I think you need to use `input_nc 1` and `output_nc 3`. Also, check out our latest [PyTorch](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix) code with [colorization](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/docs/tips.md#notes-on-colorization) mode.
