### ISSUE TITLE
how many images should testB folder contains?

### ISSUE THREAD

**Issue by chenhaibin2019** [junyanz/CycleGAN#108]
Hello, I have a question regarding the test image set up.

The original paper did mention it takes 50 images as buffer in training process. However, it did not explicitly explain how many images it need in inference. I know if I leave testB folder empty, there is division zero error. 
- I am wondering if it makes any different to use 1 or 100 pictures in testB folder,  since the weight has been learned already? 
- What is the ideal number of images in testB folder? 

thank you

**Comment by junyanz** [comment]
We also provide a model `--model test` that requires no `testB` directory for cyclegan inference. See [here](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix#apply-a-pre-trained-model-cyclegan) for more details.

**Comment by chenhaibin2019** [comment]
cool, it worked for me.
