### ISSUE TITLE
Error while running Test script

### ISSUE THREAD

**Issue by xcyan** [junyanz/CycleGAN#11]
./models/cycle_gan_model.lua:305: attempt to compare number with nil
stack traceback:
	./models/cycle_gan_model.lua:305: in function 'GetCurrentVisuals'
	test.lua:103: in main chunk

**Comment by taesung89** [comment]
Thank you for pointing that out! The bug should've been fixed. 

By the way, the option `model=one_direction_test` can be handy. The test mode for CycleGANModel is used to generate images in both directions.
