### ISSUE TITLE
only load one direction generator in GPU

### ISSUE THREAD

**Issue by JamesChenChina** [junyanz/CycleGAN#117]
As mentioned in https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/docs/qa.md, for pytorch version there is an option named --model_suffix which can load only one generator to produce the results in a single direction. This greatly saves GPU memory as we are not loading the discriminators and the other generator in the opposite direction. 
Is there similar option in torch version that can save GPU memory when testing?

**Comment by junyanz** [comment]
We have implemented a similar model [one_direction_test_model](https://github.com/junyanz/CycleGAN/blob/master/models/one_direction_test_model.lua).
