### ISSUE TITLE
Sometimes, training is stucked in epoch 72

### ISSUE THREAD

**Issue by MCDM2018** [junyanz/CycleGAN#120]
Hello guys
Above all, thanks to authors.
now, i m using cyclegan for my project. but Sometimes the training process is frozen in epoch 72. Anyone experiences this situation?

**Comment by junyanz** [comment]
Did you use the Pytorch code or Lua code?

**Comment by MCDM2018** [comment]
@junyanz  I m using pytorch code . And my pytorch version is 1.0.1

**Comment by junyanz** [comment]
This is the repo for Lua code. Could you post your question on the PyTorch repo?
