### ISSUE TITLE
Training with limited/less data

### ISSUE THREAD

**Issue by AadSah** [junyanz/CycleGAN#121]
@junyanz Sir, Is there any trick or better way to train a CycleGAN if I have very fewer data from one domain but sufficient data from the other domain?

**Comment by junyanz** [comment]
One idea is to (1) train an auto-encoder for the domain with sufficient data. (2) share the generator across two domains. See some recent work for more details [[1]](https://arxiv.org/abs/1905.01723), [[2]](https://papers.nips.cc/paper/7480-one-shot-unsupervised-cross-domain-translation.pdf).
