### ISSUE TITLE
Datasets cannot be downloaded

### ISSUE THREAD

**Issue by coditive** [junyanz/CycleGAN#123]
I cannot download the datasets for cyclegan for testing the model. Please Help!
![error](https://user-images.githubusercontent.com/41199211/66584126-318c0500-eba2-11e9-96dd-9a3b0dfe023c.png)

**Comment by junyanz** [comment]
The Berkeley EECS server seems to be down. You can find a solution in this [post](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/issues/785).

**Comment by coditive** [comment]
Thank You For your Help

**Comment by taesungp** [comment]
I am sorry about that. Recently there has been power outage in many regions in California, including UC Berkeley. It's almost resolved, and I think the system will be back up sometime on Monday in California time.
