### ISSUE TITLE
Question about training GAN

### ISSUE THREAD

**Issue by Rivendile** [junyanz/CycleGAN#129]
I found that it only forward once before update discriminator and generator per iteration in your code. However, in other papers, some forward respectively for D and G, e.g. MUNIT. Personally, I think the latter one is more reasonable. Could you please tell me what's the difference between this two kinds of pipeline? Or why do you forward only once per iteration? Thanks a lot.

**Comment by junyanz** [comment]
I didn't see a big difference regarding the quality of results between two implementations. The first one is slightly faster. If you want to do forward twice, you can just add an additional`self.forward()`.

**Comment by Rivendile** [comment]
Thanks for your reply! I think one is synchronous update, while the other is asynchronous update. It seems that the results are almost the same, as you say.

**Comment by junyanz** [comment]
Great. Feel free to try different update methods.
