### ISSUE TITLE
input_nc not used

### ISSUE THREAD

**Issue by xcyan** [junyanz/CycleGAN#13]
In models/architecture.lua

-- function defineG_resnet_9blocks(input_nc, output_nc, ngf)
--    local e1 = data - nn.SpatialReflectionPadding(p, p, p, p) - nn.SpatialConvolution(3, ngf, f, f, 1, 1) - normalization(ngf) - nn.ReLU(true)

shouldn't it be the following?

++ function defineG_resnet_9blocks(input_nc, output_nc, ngf)
++    local e1 = data - nn.SpatialReflectionPadding(p, p, p, p) - nn.SpatialConvolution(input_nc, ngf, f, f, 1, 1) - normalization(ngf) - nn.ReLU(true)

**Comment by junyanz** [comment]
Thanks for pointing out the issue. We just fixed it.
