### ISSUE TITLE
About 'L1-norm' in cycle-consistency loss function

### ISSUE THREAD

**Issue by Michi-123** [junyanz/CycleGAN#134]
Cycle-consistency loss function is using  'L1-norm'. 
I think it is because G(F(x)) is very near to domain x.  
x and x^ should be like this: 
x   [1.0, 1.0, 1.0, 0.0, 0.0, ...]
x^ [1.0, 1.0, 0.9, 0.1, 0.1, ...]
Since almost of all values should have same, the distance is near to zero. So I think L1-norm is useful than L2 norm.
Is this idea right?

**Comment by junyanz** [comment]
Both L1-norm and L2-norm can be used and results should not change a lot. L1-norm might produce slightly sharper results.

**Comment by Michi-123** [comment]
Thank you.
