### ISSUE TITLE
display error

### ISSUE THREAD

**Issue by Sugarbank** [junyanz/CycleGAN#16]
Hi I tried to run but received this error
/Users/zSUGARBANK/torch/install/bin/luajit: ...rs/zSUGARBANK/torch/install/share/lua/5.1/trepl/init.lua:389: ...rs/zSUGARBANK/torch/install/share/lua/5.1/trepl/init.lua:389: module 'display' not found:No LuaRocks module found for display
	no field package.preload['display']
	no file '/Users/zSUGARBANK/.luarocks/share/lua/5.1/display.lua'
	no file '/Users/zSUGARBANK/.luarocks/share/lua/5.1/display/init.lua'
	no file '/Users/zSUGARBANK/torch/install/share/lua/5.1/display.lua'
	no file '/Users/zSUGARBANK/torch/install/share/lua/5.1/display/init.lua'
	no file './display.lua'
	no file '/Users/zSUGARBANK/torch/install/share/luajit-2.1.0-beta1/display.lua'
	no file '/usr/local/share/lua/5.1/display.lua'
	no file '/usr/local/share/lua/5.1/display/init.lua'
	no file '/Users/zSUGARBANK/.luarocks/lib/lua/5.1/display.so'
	no file '/Users/zSUGARBANK/torch/install/lib/lua/5.1/display.so'
	no file './display.so'
	no file '/usr/local/lib/lua/5.1/display.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'error'
	...rs/zSUGARBANK/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
	test.lua:27: in main chunk
	[C]: in function 'dofile'
	...BANK/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x010402bd00

When checking it looks like I have installed this rock rock though

Christians-iMac:CycleGAN-master zSUGARBANK$ luarocks list

Installed rocks:
----------------

async
   scm-1 (installed) - /usr/local/lib/luarocks/rocks-5.2

autograd
   scm-1 (installed) - /usr/local/lib/luarocks/rocks-5.2

cwrap
   scm-1 (installed) - /usr/local/lib/luarocks/rocks-5.2

display
   scm-0 (installed) - /usr/local/lib/luarocks/rocks-5.2

image
   1.0-0 (installed) - /usr/local/lib/luarocks/rocks-5.2

lua-cjson
   2.1.0-1 (installed) - /usr/local/lib/luarocks/rocks-5.2

luaffi
   scm-1 (installed) - /usr/local/lib/luarocks/rocks-5.2

luarocks
   2.4.2-1 (installed) - /usr/local/lib/luarocks/rocks-5.2

luasocket
   3.0rc1-2 (installed) - /usr/local/lib/luarocks/rocks-5.2

matio
   scm-1 (installed) - /usr/local/lib/luarocks/rocks-5.2

nn
   scm-1 (installed) - /usr/local/lib/luarocks/rocks-5.2

nninit
   scm-1 (installed) - /usr/local/lib/luarocks/rocks-5.2

optim
   1.0.5-0 (installed) - /usr/local/lib/luarocks/rocks-5.2

paths
   scm-1 (installed) - /usr/local/lib/luarocks/rocks-5.2

sys
   1.1-0 (installed) - /usr/local/lib/luarocks/rocks-5.2

torch
   scm-1 (installed) - /usr/local/lib/luarocks/rocks-5.2

unsup
   0.1-0 (installed) - /usr/local/lib/luarocks/rocks-5.2

xlua
   1.1-0 (installed) - /usr/local/lib/luarocks/rocks-5.2

Any advice?
Could I unrequire display?

**Comment by taesung89** [comment]
You can set `display_id=0` to disable the display functionality. 

By the way, from the output it looks like Torch uses lua 5.1, while luarocks uses version 5.2. Could you check that?

**Comment by Sugarbank** [comment]
is this a flag or is it in one of the lua scripts?

**Comment by junyanz** [comment]
It is a flag.

**Comment by Sugarbank** [comment]
hmmm I try this

DATA_ROOT=./datasets/ae_photos name=style_cezanne_pretrained model=one_direction_test phase=test loadSize=256 fineSize=256 resize_or_crop="scale_width" display_id=0 th test.lua


but still get the same error.
Am I setting the flag correctly?

**Comment by taesung89** [comment]
That looks like a [bug](https://github.com/junyanz/CycleGAN/blob/master/util/visualizer.lua#L8). We will fix it soon. Thank you for pointing that out.

**Comment by junyanz** [comment]
I just fixed the bug. Let me if it works for you.
