### ISSUE TITLE
Pytorch version

### ISSUE THREAD

**Issue by rogertrullo** [junyanz/CycleGAN#22]
Thanks for posting your work!! Just wondering approximately when would the pytorch version be available?

**Comment by junyanz** [comment]
Hi rogertrullo, we are currently working on the pytorch implementation of CycleGAN and pix2pix, and hopefully we can release a beta version by this Sunday.  Sorry about the delay as it takes longer than we expect to finish.

**Comment by rogertrullo** [comment]
:+1: Thanks!! looking forward to it :)

**Comment by junyanz** [comment]
The Pytorch version of CycleGAN and pix2pix is almost done. We are currently doing experiments to see if the Pytorch implementation can reproduce the results in the paper.

**Comment by rogertrullo** [comment]
Thank you!!!

**Comment by junyanz** [comment]
Please check out the [PyTorch] (https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/) version here. It is still work in progress. Please use the Torch implementation if you would like to reproduce the exact same results in the paper.
