### ISSUE TITLE
CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by whatru** [junyanz/CycleGAN#23]
When I run: DATA_ROOT=./datasets/ae_photos name=style_cezanne_pretrained model=one_direction_test phase=test loadSize=256 fineSize=256 resize_or_crop="scale_width" gpu=0 th test.lua

It comes:
...
Cleaning up temporary files
Dataset Size B: 	205	
use InstanceNormalization	
loading previously trained model (/Users/Y/CycleGAN/checkpoints/style_cezanne_pretrained/latest_net_G.t7)	
use InstanceNormalization	
THCudaCheck FAIL file=/tmp/luarocks_cutorch-scm-1-7004/cutorch/lib/THC/THCGeneral.c line=66 error=35 : CUDA driver version is insufficient for CUDA runtime version
/Users/Y/torch/install/bin/luajit: /Users/Y/torch/install/share/lua/5.1/trepl/init.lua:389: /Users/Y/torch/install/share/lua/5.1/trepl/init.lua:389: cuda runtime error (35) : CUDA driver version is insufficient for CUDA runtime version at /tmp/luarocks_cutorch-scm-1-7004/cutorch/lib/THC/THCGeneral.c:66
stack traceback:
	[C]: in function 'error'
	/Users/Y/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
	/Users/Y/CycleGAN/util/util.lua:189: in function 'load_test_model'
	./models/one_direction_test_model.lua:23: in function 'Initialize'
	test.lua:79: in main chunk
	[C]: in function 'dofile'
	...nggy/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x010f30da00

Why will it come out? Any one can help me?
OS: 10.12.4
CUDA: 8.0.61
Xcode: 8.2 (CUDA (v8.0.61) does not yet support Xcode 8.3)

**Comment by HilmiK** [comment]
Has anyone solved this ? I have CUDA 8.0 and CUDNN 7.0
