### ISSUE TITLE
Torch-CL support?

### ISSUE THREAD

**Issue by cathalgarvey** [junyanz/CycleGAN#27]
This looks really fun to play with, thanks!

Any reason to think this wouldn't work with Torch-CL, if all occurances of `:cuda()` were just replaced with `:cl()`?

(more and more reasons to just drop the two methods and have a generic `:gpu()` method, IMO...)

**Comment by junyanz** [comment]
That would be great. Could you create a pull request on it?

**Comment by victor-felicitas** [comment]
Unfortunately, I couldn't even launch any model with Torch-cl in CPU mode. It results in mistake about missing nn module, even after certain install of nn and nn graph. 

Usual torch works fine in CPU mode, albeit too slow (on Ryzen 1600X it takes ~30 min to train on 50 images with 256X256 resolution).
