### ISSUE TITLE
Loading and testing only a trained fakeA or fakeB model?

### ISSUE THREAD

**Issue by Quasimondo** [junyanz/CycleGAN#29]
I'm wondering if there is already an option in place that does only load one of the generator models for the purpose of processing images after training? It seems like right now the test.lua script and the model classes will always load all the models and thus using GPU memory that could otherwise be used for processing bigger input sizes.

I'm not sure if that even possible or if the CycleGAN process always requires both models even in test mode?

**Comment by Quasimondo** [comment]
I had a look at the code and made some small adjustments that allow to only load/run net_G_A or net_G_B in test mode. This allows to apply the learned transformation to bigger input images:

The new option is opt.which_models and can be either "A","B" or "AB". In training mode it should always be "AB":
https://github.com/Quasimondo/CycleGAN/blob/master/models/cycle_gan_model.lua
https://github.com/Quasimondo/CycleGAN/blob/master/options.lua

**Comment by junyanz** [comment]
@Quasimondo  Thanks for sharing your code. Our [one_direction_test_model.lua](https://github.com/junyanz/CycleGAN/blob/master/models/one_direction_test_model.lua)  was actually implemented for this purpose. See [test_vangogh_style_on_ae_photos.sh](https://github.com/junyanz/CycleGAN/blob/master/examples/test_vangogh_style_on_ae_photos.sh) for an example usage.
