### ISSUE TITLE
provide minimum nVidia hardware info to reproduce results for each dataset

### ISSUE THREAD

**Issue by atti-dall-atto** [junyanz/CycleGAN#31]
You state that various CUDA components are required, but you nowhere state in the Readme.md or your paper the minimum GPU hardware requirements to reproduce your results.

i.e.

_Minimum Compute Architecture_
is it OK to use the lowest that CUDA 7/8 supports, e.g. Fermi (3.5), or do you use FP16 unconditionally and hence require 5.3 or higher ?

_Minimum GPU memory_
how much on-card memory is required to even load your tutorial datasets ?

**Comment by junyanz** [comment]
We used CUDA 8, cuDNN 5.1, and GTX 1080 (8GB memory) in our experiments. We used the default settings. 8GB should be enough for training a model on 256x256 images. We haven't tested other hardware.
