### ISSUE TITLE
attempt to call global 'unpack' (a nil value)

### ISSUE THREAD

**Issue by yeguixin** [junyanz/CycleGAN#33]
/home/gxy/install_package/torch/install/bin/lua: ./util/plot_util.lua:23: attempt to call global 'unpack' (a nil value)
stack traceback:
        ./util/plot_util.lua:23: in function 'Initialize'
        train.lua:81: in main chunk
        [C]: in function 'dofile'
        ...kage/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
        [C]: in ?
---------------------------------------------------------------------------------------------------------------------
When you are use Lua5.2. It should modify ./util/plot_util.lua the 23th line, as follow:
-labels={'epoch', unpack(self.display_plot)},
+labels={'epoch', table.unpack(self.display_plot)},

**Comment by junyanz** [comment]
Thanks a lot. I added a `local unpack = unpack or table.unpack` to address this compatibility issue. Let me know if it works for Lua 5.2.

**Comment by yeguixin** [comment]
Yes, it works.

**Comment by junyanz** [comment]
Thanks @yeguixin!
