### ISSUE TITLE
How to train pix2pix model using CycleGAN?

### ISSUE THREAD

**Issue by yeguixin** [junyanz/CycleGAN#34]
Does it train pix2pix model? If it can do so, how to prepare the train sets? Thanks

**Comment by junyanz** [comment]
This is the Torch implementation for CycleGAN. Please see the [Torch](https://github.com/phillipi/pix2pix) and [PyTorch](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix) implementation of pix2pix. Check this [documentation](https://github.com/phillipi/pix2pix#setup-training-and-test-data) on train dataset preparation

**Comment by yeguixin** [comment]
Another question. there is no th option "resize_or_crop" in train.lua in pix2pix. The size of my train picture is 150*70pixel. Should I set the loadSize=150 and fineSize=150 when training using pix2pix?

**Comment by junyanz** [comment]
Yes, the 'resize_and_crop' option is currently only available at PyTorch version. You can set loadSize=150 and fineSize=150 if you want to use the Torch code.

**Comment by phillipi** [comment]
Yeah, setting `loadSize=150` will resize the image to a 150x150 square. You probably want to set fineSize to something like 130. `fineSize` specifies the size of random crops from the loaded images. So setting `loadSize=150` and `fineSize=130` will take random 130x130 crops from the 150x150 resized images.

**Comment by yeguixin** [comment]
Ok, Thanks a lot
