### ISSUE TITLE
Memory usage increases with epochs

### ISSUE THREAD

**Issue by rbrth** [junyanz/CycleGAN#35]
Hi junyanz,

Thanks for releasing the code, very cool work. Awesome!

I am having a memory issue, or perhaps it is normal that you know of. With each epoch, GPU memory usage seems to increase. After a while, the limit (12GB) is reached and the learning terminates. 

Is there a way to circumvent this? I currently just reduce the number of filters, but it is hard to estimate how many epoch I can run until it crashes.

Best,
Ruud

**Comment by junyanz** [comment]
Interesting. Which resolution is your model? What's the initial memory usage?

**Comment by rbrth** [comment]
Hi Junyanz, 

I crop the images to 424x424.

Currently I have found a number of filters that fits my GPU memory. It'll still increase over time, but stays within the limit.

I will try to get investigate further how the memory increase behaves as a function of number of filters.

Best,
Ruud

**Comment by junyanz** [comment]
You can also try `loadSize=424` and `fineSize=256`. This will largely ease the memory burden. You can run `256x256` model on the full image during the testing.

**Comment by rbrth** [comment]
Great idea and solution! 

I assume that the cropping is a randomly translated 256x256 sub-frame in the 424x424 image frame? Or is it fixed (centered, cornered)?

Best,
Ruud

**Comment by junyanz** [comment]
It's a random crop.

**Comment by rbrth** [comment]
"You can run 256x256 model on the full image during the testing."

Not sure if that works. When I do run the cropped model (256x256) on the full image (424x424) during testing, then I also run out of memory. 

Anyway, I can revert to my old training and testing with less filters and full image. That'll work too. :-)

**Comment by junyanz** [comment]
Cool. I am glad that it works with your tricks.
