### ISSUE TITLE
may I input rectangle pictures?（not square,128pixels*128pixels）

### ISSUE THREAD

**Issue by zhanary** [junyanz/CycleGAN#41]
My pictures are not square, but the code will resize and crop my pictures to be 128*128
How can I change it?
Thank you   : ) 
@junyanz

**Comment by junyanz** [comment]
You can set `resize_and_crop=crop`. The program will then only crop `fineSize x fineSize` patches without rescaling the input images.

**Comment by zhanary** [comment]
I try to use `resize_and_crop=crop`,but it still cut my pictures to be squared and small(128*128)

then I change the `options.luabut`—— `fineSize = 256`, it makes error 

`#training iterations: 200	
THCudaCheck FAIL file=/root/torch/extra/cutorch/lib/THC/generic/THCStorage.cu line=66 error=2 : out of memory
/root/torch/install/bin/luajit: /root/torch/install/share/lua/5.1/nn/THNN.lua:110: cuda runtime error (2) : out of memory at /root/torch/extra/cutorch/lib/THC/generic/THCStorage.cu:66
stack traceback:
	[C]: in function 'v'
	/root/torch/install/share/lua/5.1/nn/THNN.lua:110: in function 'SpatialFullConvolution_updateGradInput'
	...orch/install/share/lua/5.1/nn/SpatialFullConvolution.lua:130: in function 'updateGradInput'
	/root/torch/install/share/lua/5.1/nngraph/gmodule.lua:420: in function 'neteval'
	/root/torch/install/share/lua/5.1/nngraph/gmodule.lua:454: in function 'updateGradInput'
	./models/cycle_gan_model.lua:201: in function 'fGx_basic'
	./models/cycle_gan_model.lua:217: in function 'opfunc'
	/root/torch/install/share/lua/5.1/optim/adam.lua:37: in function 'adam'
	./models/cycle_gan_model.lua:236: in function 'OptimizeParameters'
	train.lua:137: in main chunk
	[C]: in function 'dofile'
	/root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00406670
`

but I don't want to cut my pictures to be squared, I want to use 640*480 ,not 128*128, how can I change it?
Thank you very much~! @junyanz

**Comment by junyanz** [comment]
It currently only supports square images during the training time. But during the test time, as the model is fully convolutional, you can run the `128x128` model on the full image, (set `resize_and_crop=scale_width or scale_height`) and the program will process the entire test image.

**Comment by zhanary** [comment]
Thank you for your reply~
Can I change the `fineSize `=256 or 512?

**Comment by junyanz** [comment]
I think `fineSize` should be smaller than your image size and `loadSize`. The program will crop `fineSize x fineSize` windows from the input images.

**Comment by zhanary** [comment]
It works！ Thank you very much! @junyanz

**Comment by mhusseinsh** [comment]
so I cannot use any rectangle images ?
