### ISSUE TITLE
Option for cache location

### ISSUE THREAD

**Issue by Fex021** [junyanz/CycleGAN#45]
Hello,

I tried to run CycleGAN in a Singularity Container on our cluster. If the normal user runs this container (and therefore CycleGAN) he is not allowed to change the container. Unfortunately the creation of the cache directory for the training metadata in the file `data/donkey_folder.lua` does not work. It says something like "mkdir cannot create directory".

1. I don't know how much the cache speeds up the computation? The training ran without cache (I hope succesfully). Does CycleGAN need the cache?

2. Can you introduce an option for the location of the cache directory analogue to the options for results_dir and checkpoints_dir? If I can specify a cache directory by an absolute path my Singularity container could create that cache.

The code in `data/donkey_folder.lua` I mean is:

```
-- a cache file of the training metadata (if doesnt exist, will be created)
local cache = "cache"
local cache_prefix = opt.data:gsub('/', '_')
os.execute('mkdir -p cache')
local trainCache = paths.concat(cache, cache_prefix .. '_trainCache.t7')
```

**Comment by junyanz** [comment]
Fixed. I just added a flag called `cache_dir`.

**Comment by Fex021** [comment]
Thank you!
