### ISSUE TITLE
Visualize the middle layers

### ISSUE THREAD

**Issue by amirid** [junyanz/CycleGAN#46]
Hi,
How can I get the values of the middle layers to visualize them in generator? (for example in defineG_encoder_decoder function.)

**Comment by junyanz** [comment]
You need to modify the model definition in the `models/architectures.lua`. In particular, you probably need to add the values of desired middle layers to the module output ` local netG = nn.gModule({e1},{o1, your_middle_output})`.

**Comment by amirid** [comment]
Thank you. I think this way I can extract data from middle layers in training phase. What if I want to extract data in test phase ( when a pre-trained model is available).

**Comment by junyanz** [comment]
I think in torch you can define your own network, and initialize the weights with another pre-trained network.
