### ISSUE TITLE
attempt to index global 'jit' (a nil value)

### ISSUE THREAD

**Issue by kmader** [junyanz/CycleGAN#5]
Does not work with Lua52 (not LuaJit) which I used to get around memory issues (https://github.com/OpenNMT/OpenNMT/issues/20)

Full error message
```
/Users/mader/torch/install/bin/lua: ...rs/mader/torch/install/share/lua/5.2/threads/threads.lua:183: [thread 1 callback] /Users/mader/Dropbox/Informatics/CycleGAN/data/dataset.lua:148: attempt to index global 'jit' (a nil value)
```

**Comment by ellcyyang** [comment]
maybe the same error?
I tried with lua5.1 but got the same error.

DataLoader UnalignedDataLoader was created.	
Starting donkey with id: 1 seed: 9108
table: 0x7efcb8160dc0
table: 0x7efcb83f02e0
/home/ubuntu/torch/install/bin/lua: ...e/ubuntu/torch/install/share/lua/5.2/threads/threads.lua:183: [thread 1 callback] /home/ubuntu/CycleGAN/data/dataset.lua:148: attempt to index global 'jit' (a nil value)
stack traceback:
	/home/ubuntu/CycleGAN/data/dataset.lua:148: in function '__init'
	/home/ubuntu/torch/install/share/lua/5.2/torch/init.lua:91: in function </home/ubuntu/torch/install/share/lua/5.2/torch/init.lua:87>
	[C]: in function 'dataLoader'
	/home/ubuntu/CycleGAN/data/donkey_folder.lua:183: in main chunk
	[C]: in function 'dofile'
	/home/ubuntu/torch/install/share/lua/5.2/paths/init.lua:84: in function 'dofile'
	/home/ubuntu/CycleGAN/data/data.lua:39: in function </home/ubuntu/CycleGAN/data/data.lua:29>
	(...tail calls...)
	[C]: in function 'xpcall'
	...e/ubuntu/torch/install/share/lua/5.2/threads/threads.lua:234: in function 'callback'
	/home/ubuntu/torch/install/share/lua/5.2/threads/queue.lua:65: in function </home/ubuntu/torch/install/share/lua/5.2/threads/queue.lua:41>
	[C]: in function 'pcall'
	/home/ubuntu/torch/install/share/lua/5.2/threads/queue.lua:40: in function 'dojob'
	[string "  local Queue = require 'threads.queue'..."]:13: in main chunk
stack traceback:
	[C]: in function 'error'
	...e/ubuntu/torch/install/share/lua/5.2/threads/threads.lua:183: in function 'dojob'
	...e/ubuntu/torch/install/share/lua/5.2/threads/threads.lua:264: in function 'synchronize'
	...e/ubuntu/torch/install/share/lua/5.2/threads/threads.lua:142: in function 'specific'
	...e/ubuntu/torch/install/share/lua/5.2/threads/threads.lua:125: in function <...e/ubuntu/torch/install/share/lua/5.2/threads/threads.lua:36>
	(...tail calls...)
	/home/ubuntu/CycleGAN/data/data.lua:27: in function 'new'
	/home/ubuntu/CycleGAN/data/data_util.lua:17: in function 'load_dataset'
	./data/unaligned_data_loader.lua:24: in function 'Initialize'
	test.lua:47: in main chunk
	[C]: in function 'dofile'
	...untu/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: in ?

**Comment by junyanz** [comment]
I followed the torch.dcgan's [fix](https://github.com/soumith/dcgan.torch/commit/f709ad999d8e5f13457b0a0a7c2d7d8c4ffa8696). Let me know if it works for you guys.

**Comment by Amyhii** [comment]
Thank you so much. It worked for me with Lua 5.2
