### ISSUE TITLE
Image request

### ISSUE THREAD

**Issue by hdnse4798** [junyanz/CycleGAN#51]
Can you give me the original images (format: .jpg, .png or .bmp)? Thanks a lot.
link: https://github.com/junyanz/CycleGAN/blob/master/imgs/horse2zebra.gif

**Comment by junyanz** [comment]
Please send us an email for the original images.

**Comment by hdnse4798** [comment]
m10507502@mail.ntust.edu.tw
Thanks a lot.

**Comment by zhangqian001** [comment]
> [m10507502@mail.ntust.edu.tw](mailto:m10507502@mail.ntust.edu.tw) Thanks a lot.

你好，冒昧打扰，想请教下您如何实现在gif或者视频上的图像翻译呢。
