### ISSUE TITLE
The scale of generated image

### ISSUE THREAD

**Issue by hankobe** [junyanz/CycleGAN#56]
Hi Mr. Zhu,
        Your results are powerful and attract me deeply.
        But I have a question, the scale of generated image is too small (only 128*128), do you have some idea to transform arbitrary scale of image as input ?

**Comment by junyanz** [comment]
We can generate images like `256x256` or `512x512`. It also works for images with arbitrary sizes. For more details, please check out `loadSize`, `fineSize`, and `resize_or_crop` flags in the [option.lua](https://github.com/junyanz/CycleGAN/blob/master/options.lua)
