### ISSUE TITLE
Once I run torch code on a multi-gpu machine. It slows down over 100% ! 

### ISSUE THREAD

**Issue by LambdaWill** [junyanz/CycleGAN#58]
When the I run your code on a machine which has single GPU, the speed is fast. However,
when try running it on a machine which has multiple GPUs, it slows down **over 100%**!
I find that other gpus all have ~300Mb memory usages occpied by the same thread. I think whether it is the bottleneck of the decrease. How to solve it?

**Comment by phillipi** [comment]
In a shell, you can use 'export CUDA_DEVICES_VISIBLE=0' to make it so the session only knows about the gpu with ID 0, and then everything will run on just one gpu and should be as fast as if you really only had a single gpu.

**Comment by LambdaWill** [comment]
![1](https://user-images.githubusercontent.com/26055298/31813794-2d0a7630-b5ba-11e7-89bb-96fefa7c4472.png)
I follow your advice,  'export CUDA_DEVICES_VISIBLE=5' and run the code `gpu=6 th train.lua`. However, it doesn't make any differences.

**Comment by phillipi** [comment]
oops, I had a typo above, it should be CUDA_VISIBLE_DEVICES (now corrected above). Also, you don't need to set `gpu=6` above. Torch will reindex the gpus so that it thinks the gpu with ID 5 is now gpu 0.

**Comment by LambdaWill** [comment]
You are right! Thank you.

**Comment by MalindaVania** [comment]
@LambdaWill : hi lambdaWill..do you use this torch code to run in multiple gpu? How yu do that, I tyr to put parameter GPU=0,1,2 but when I execute the code it give me error.

**Comment by LambdaWill** [comment]
@MalindaVania Aha, my code is derived from this repo, I run my own code.

**Comment by MalindaVania** [comment]
Ah..do you mind to share your code? I mean which part to change to make it
run into multiple GPU.

**Comment by LambdaWill** [comment]
@MalindaVania https://github.com/soumith/imagenet-multiGPU.torch   I drew inspiration from this repo.

**Comment by MalindaVania** [comment]
Thank you ^^
