### ISSUE TITLE
dataset: iphone2dslr_flower

### ISSUE THREAD

**Issue by ydnaandy123** [junyanz/CycleGAN#59]
Very awesome work!
I want to try more different datasets.
In the paper you say **'iphone2dslr_flower'** was collected from flickr.
How did you separate flowers with different depth of field?
Did you manually select  them or any keyword was used for search?
I'll be glad if you reply me~

**Comment by junyanz** [comment]
You can find the dataset [here](https://github.com/junyanz/CycleGAN#datasets). 
According to the [paper](https://arxiv.org/pdf/1703.10593.pdf), "Flower images taken on iPhones were downloaded from Flickr by searching for the photos taken by Apple iPhone 5, 5s, or 6, with search text flower. DSLR images with shallow DoF were also downloaded from Flickr by search tag flower, dof. The images
were scaled to width 360 pixels."
