### ISSUE TITLE
The weather or seasons convert each other

### ISSUE THREAD

**Issue by cuimiao187561** [junyanz/CycleGAN#60]
CycleGAN turn weather or season?　such as  sunny-dusk,spring-summer,daylight-bright,and so on 
![qq 20171120113615](https://user-images.githubusercontent.com/23358104/33001457-0ba4d8fe-cde9-11e7-8919-a2e8902083ea.jpg)

**Comment by junyanz** [comment]
Probably. You are free to try it.

**Comment by cuimiao187561** [comment]
I want to train day to night, do I need to download day and night pictures for training network?Similar training summer to winter, winter to summer,As shown below
![qq 20171120121014](https://user-images.githubusercontent.com/23358104/33001996-59875544-cdec-11e7-82ad-c1f228a86cb5.jpg)

**Comment by junyanz** [comment]
You can find some datasets [here](https://github.com/junyanz/CycleGAN#datasets) including summer<->winter. Also feel free to try the code on your own datasets.
