### ISSUE TITLE
Training Resolution

### ISSUE THREAD

**Issue by Sugarbank** [junyanz/CycleGAN#62]
Hi,
could you confirm the flags and parameters to set for training at a resolution of 512x512?
(Both image pairs are 512x512)
And testing at the same and higher resolution.

Cheers:)

**Comment by junyanz** [comment]
It actually depends on your applications and GPU memory. 
If you have a GPU with 20GB, you can just set `--loadSize 572 fineSize 512` for both training and test. 
If you have a GPU with 10GB, you can train a model on cropped patches. In this case, you can set `--loadSize 512 fineSize 256` for training, and set `--loadSize 512 fineSize 512` for test. The model consumes much less memory during the test time, and the fully convolutional network can work for images with arbitrary sizes
