### ISSUE TITLE
why does not the discriminator output a scalar

### ISSUE THREAD

**Issue by breadbread1984** [junyanz/CycleGAN#66]
As far as I understand, the output of the discriminator outputs a scalar which represents whether the input comes from natural image set or generated image set. But I find that your discriminator outputs a 32x32 tensor. Could you explain the reason of that? Thx

**Comment by phillipi** [comment]
This is because we use a "PatchGAN" discriminator, described in Section 3.2.2 of [this paper](https://arxiv.org/abs/1611.07004). See more details here: https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/issues/39

**Comment by knaffe** [comment]
I have a question on the implement of PatchGAN. In the Section 3.2.2 of the paper motioned above, it said 

> We run this discriminator convolutationally across the image, averaging all responses to provide the ultimate output of D.

But I couldn't find anywhere to implement of this averaging operation?
In the code, the D outputs the 30x30x1, and the loss of D is calculated by the GANLoss function(MSE or BCE loss). So, where does the averaging operation? Maybe I miss something.
Thank you !

**Comment by junyanz** [comment]
MSELoss has been shown to be more stable than the vanilla GAN loss. See this [paper](https://arxiv.org/abs/1611.04076) for more details.
