### ISSUE TITLE
lambda_A and lambda_B

### ISSUE THREAD

**Issue by limchaos** [junyanz/CycleGAN#68]
I mean what's the matter if  I set a big lambda_A ,  thanks XD .

**Comment by junyanz** [comment]
lambda_A and lambda_B are weights for cycle-consistency loss (regularization term). A bigger lambda will lead to better reconstruction loss, but also smaller changes. A smaller lambda will allow the model to bring more dramatic changes to the input images, with the risk of artifacts. I will recommend you set it as 1 to 10.

**Comment by limchaos** [comment]
thanks (ฅ>ω<*ฅ)
