### ISSUE TITLE
Sigmoid for lsgan

### ISSUE THREAD

**Issue by fanpengustc** [junyanz/CycleGAN#70]
Why sigmoid is not used in Discriminator for lsgan, if that has some special meaning？

**Comment by junyanz** [comment]
Sigmoid activation is removed in the LSGAN. Otherwise, there might be vanishing gradient issue. See this [post](https://wiseodd.github.io/techblog/2017/03/02/least-squares-gan/) for more details.

**Comment by fanpengustc** [comment]
Thanks for your answer! But in the post, I did not find the sigmoid activation is removed!

**Comment by junyanz** [comment]
You can find details in the 'LSGAN implementation in Pytorch' section. There is a comment saying ` # No sigmoid`.

**Comment by fanpengustc** [comment]
Thanks!
