### ISSUE TITLE
Result of cezanne_pretrained looking like heatmaps

### ISSUE THREAD

**Issue by totopia** [junyanz/CycleGAN#71]
Ran commands:
````
bash ./datasets/download_dataset.sh ae_photos
bash ./pretrained_models/download_model.sh style_cezanne
DATA_ROOT=./datasets/ae_photos name=style_cezanne_pretrained model=one_direction_test phase=test loadSize=256 fineSize=256 resize_or_crop="scale_width" th test.lua
````

Result: 

![style_cezanne_pretrained](https://user-images.githubusercontent.com/11430492/36064571-f348abfc-0e5a-11e8-89b3-c6220fcb7c03.png)

Is it expected?

**Comment by junyanz** [comment]
It is not expected. It is caused by Torch version. I resolved the issue by removing the old torch and installing a new torch from the scratch following this official instruction.
See #57 for more discussion.

**Comment by totopia** [comment]
Thanks for the reply.
seems like I may have more infra problems to solve before I can get Torch re-installed. 
Could you let me know your output for `cd ~torch; git log -n 1`? This should display the "version" of torch.

Somehow the very edge commit has the openblas_utest taking forever on installl on Ubuntu 16.04, but it may be my own env issues.

**Comment by junyanz** [comment]
Here is my torch version: commit 20e523771377568841e9d11bc3275a4404edcd1e

**Comment by totopia** [comment]
@junyanz Thanks for the info. I tried the commit and it doesn't seem to be specific to torch itself. It might be a deeper issure in gcc or nvcc. 
Do you know which Cuda version you were using at the time of training the model?
I also realize that if I train my own models, this problem goes away, so it must be something with dependencies instead of the app code.

**Comment by junyanz** [comment]
Cool. I am using cuda 8.0. I always a complete re-installation. I am never able to fix a broken Torch.
