### ISSUE TITLE
video

### ISSUE THREAD

**Issue by 994088895** [junyanz/CycleGAN#75]
I want to know how to turn a horse video into a zebra video by cyclegan. Does it need to edit it by frame to frame? Does it nedd to align and crop and how to keep consistent with original frame in size and some other content? Thank you

**Comment by junyanz** [comment]
We just run the model frame by frame. We use the following script. 
```
DATA_ROOT=./datasets/horse_frames/ name=horse2zebra_pretrained model=one_direction_test phase=test loadSize=256 fineSize=256 resize_or_crop="scale_width" th test.lua
```

**Comment by 994088895** [comment]
Thank you!

**Comment by zhangqian001** [comment]
> Thank you!

hello, I also want to do video in the translation model, does you achieve it or not? thank you very much.

**Comment by zhangqian001** [comment]
> 
Hello, thank you for your excellent work, I have some question about generate horse2zebra video. So how can i run this model frame by frame. look forward to your reply.
