### ISSUE TITLE
Wasserstein Distance

### ISSUE THREAD

**Issue by MalindaVania** [junyanz/CycleGAN#76]
Hi, I would like to use the Wasserstein Distance. Which part should I change? Do I need to make new model file? Thank you.

**Comment by junyanz** [comment]
Depends on the version. 
For Pytorch, you can borrow some code from this wgan [repo](https://github.com/caogang/wgan-gp) and modify this [file](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/models/cycle_gan_model.py#L100).
For Lua, you can modify this [file](https://github.com/junyanz/CycleGAN/blob/master/models/cycle_gan_model.lua#L136).

**Comment by rohitsaluja22** [comment]
hey @MalindaVania

**Comment by MalindaVania** [comment]
Thank you for reply, I'll try to implement it ^^

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Best regards.

Malinda Vania

*Bionics Research Centre*


*Biomedical EngineeringKorea Institute of Science and Technology
(KIST)Hwarangno 14-gil 5, Seongbuk-gu, Seoul, 136-791, Korea*
*서울특별시 성북구 화랑로 14길 5 (하월곡동, 한국과학기술연구원)*
*Email : malinda.vania@gmail.com <yohanakurniaendah1986@gmail.com>*
*Phone : 010-2611-1889*
