### ISSUE TITLE
Epoch_size

### ISSUE THREAD

**Issue by siyazingca** [junyanz/CycleGAN#80]
I would like to know which file that contains the epoch size for training

**Comment by junyanz** [comment]
[ntrain](https://github.com/junyanz/CycleGAN/blob/master/options.lua#L20) controls the maximum number of images per epoch. [niter](https://github.com/junyanz/CycleGAN/blob/master/options.lua#L16) and [niter_decay](https://github.com/junyanz/CycleGAN/blob/master/options.lua#L17) controls the number of epoches in the training.
