### ISSUE TITLE
Can I implement this on Caffe?

### ISSUE THREAD

**Issue by JackWolftoMc** [junyanz/CycleGAN#81]
Recently I work on caffe to do stuff like ioit, as a freshman in DL, unfortunately I can't find Caffe models about itot. I'm wondering if I can implement this on Caffe? Or I'd better turn and join to the streams of Pytorch? Any ideas may be helpful, thx a lot.

**Comment by junyanz** [comment]
It is possible according to this [post](https://www.quora.com/Can-I-make-Generative-Adversarial-Network-using-Caffe). I think Pytorch is just fine as PyTorch will use caffe2 as backend soon.
