### ISSUE TITLE
Discriminator's output shape [1,6,6,1]?  

### ISSUE THREAD

**Issue by zhuqunxi** [junyanz/CycleGAN#84]
five layer
padding: 1,1,1,1,1           
stride: 2,2,2,1,1
![image](https://user-images.githubusercontent.com/22273557/38748919-61b5acfe-3f82-11e8-8c84-eda65b052a77.png)

**Comment by junyanz** [comment]
I guess it depends on your input/output image sizes.

**Comment by zhuqunxi** [comment]
As a beginner in the field of Deep Learning, it is my great honor to receive your  response. But I  still have  trouble in the default sizes of input and/or output images in the discriminator.   The input image size is (1, 70,70, 3)  through resizing the original image with size (1,256,256,3). Then it is fed into the discriminator model: C64-C128-C256-C512,  as you illustrated in your pape, resulting in an output image with the size (1,6,6,1).   I  am thereby a little bit confused that why it is not a probability value/scalar but a matrix/tensor?

**Comment by junyanz** [comment]
The input image size is 256x256. The output of 70x70 patch Discriminator is around 30x30. It is a matrix.
