### ISSUE TITLE
To run dataset.lua you need "gfind" and "gwd" for OSX: brew coreutils findutils

### ISSUE THREAD

**Issue by subzerofun** [junyanz/CycleGAN#9]
Love your project, thanks for putting it online!

As the titles states, please add a small OSX segment to "Prerequisites" in the Readme, something like:

> To execute `data/dataset.lua` you need the Linux/GNU commands `gfind` and `gwc`, which can be installed with `brew install findutils coreutils`.

 
Otherwise you will get these errors:
```
(...)
/tmp/lua_iAPGkD: line 1: gfind: command not found
(...)
sh: gwc: command not found
````
---

**Another OSX quirk:** When trying the first training example (horse2zebra), i had to run the command
`DATA_ROOT=./datasets/horse2zebra name=horse2zebra_model th train.lua`
with `sudo`, without it i got this error:
```
(...)
/YOUR-TORCH-PATH/torch/install/bin/luajit: ./options.lua:132: attempt to index global 'fd' (a nil value)
stack traceback:
	./options.lua:132: in function 'parse_options'
	train.lua:14: in main chunk
	[C]: in function 'dofile'
	...avid/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x0105390360
```

**Comment by junyanz** [comment]
Thanks Subzerofun. I updated the README according to your suggestions.

**Comment by subzerofun** [comment]
Thanks!
