### ISSUE TITLE
Other Frameworks

### ISSUE THREAD

**Issue by mhusseinsh** [junyanz/CycleGAN#92]
Hello,

as far as I know that you implemented CycleGAN using torch.
I found on your project's page, that there are other implementations using other frameworks like Pytorch, Tensorflow, etc ..
My question is, are these implementations are from your side ? I mean, are they reliable and performing the same functionality/results of CycleGAN or Pix2pix ? because for example I see 4 different implementations using Tensorflow, so what is the difference exactly in something like that ?

Thanks in advance

**Comment by junyanz** [comment]
The [PyTorch](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix) one was written by the paper authors. The PyTorch implementation produces results comparable to or better than this Torch version. For Tensorflow, we haven't tested the qualify of results by ourselves. But some of them look quite good (e.g., [1](https://github.com/leehomyc/cyclegan-1), [2](https://github.com/LynnHo/CycleGAN-Tensorflow-PyTorch), [3](https://github.com/vanhuyz/CycleGAN-TensorFlow). etc.)

**Comment by mhusseinsh** [comment]
Thanks a lot for your reply.
I think I will go first with one of the versions from TensorFlow and give it a try, then I will go for the PyTorch one.

**Comment by junyanz** [comment]
Sounds great.
