### ISSUE TITLE
Tensorflow implementation

### ISSUE THREAD

**Issue by mhusseinsh** [junyanz/CycleGAN#96]
Hello,
I am really stuck in a problem, which is a little bit urgent for me
Did you have a look on this implementation of TensorFlow before, that you are attaching it to your project's page ?
https://github.com/leehomyc/cyclegan-1

I know that it is not your code or so, but I tried to contact the authors a lot, and they don't care or reply, and I am stuck in understanding something, so maybe I thought you can help me if possible
@junyanz

**Comment by junyanz** [comment]
I haven't looked at the code. Maybe you can send an email to the Tensorflow authors (@leehomyc) or use a different Tensorflow implementation.

**Comment by leehomyc** [comment]
Hi I just replied. Please let me know if there are other questions. Thanks,

**Comment by mhusseinsh** [comment]
Thanks @leehomyc 
I checked your email and replied too
